name: prebidjs-exchange-test
on: [push]
jobs:
  test-emx-adapter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: gulp build --modules=emx_digitalBidAdapter,appnexusBidAdapter
      - run: gulp test --file "test/spec/modules/emx_digitalBidAdapter_spec.js" 
      - run: node exchange_test.js
